server:
  port: 8080
  servlet:
    context-path: /youtube-integration

spring:
  application:
    name: youtube-integration
  cache:
    type: simple
  config:
    import: "optional:classpath:.env"

youtube:
  api:
    key: ${YOUTUBE_API_KEY} # Set this in your .env file
    base-url: https://www.googleapis.com/youtube/v3
    max-results: 1

  channels:
    - UCV3L1bFJs0Wn-Rmp9cVfPWg  # Replace with your channel ID

app:
  scheduler:
    youtube:
      interval: 300000 # 5 minutes

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    org.springframework.web.reactive.function.client: DEBUG
    com.ethio_connect.youtubeintegration: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info